### ISSUE TITLE
Is there a way to distinguish between Pilot and CPG in the AH-64D?

### ISSUE THREAD

**Issue by Shaftoe62** [asherao/DCS-Scripting-Environment#2]
Is there a way to distinguish between Pilot and CPG in the AH-64D?

Thank you.

**Comment by asherao** [comment]
You may have to be more specific. Which parts need distinguishing? If it has to do with the switches or buttons, that will be up to the devs. In this case ED.

**Comment by Shaftoe62** [comment]
I mean if you, as the player, have the pilot or CPG role selected. (1 or 2 keyboard)

**Comment by asherao** [comment]
Not that I know of.
